-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 5.7
-- Wed May 26 16:40:34 2021

-- parameterized module component declaration
component P3038DM_PLL
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : P3038DM_PLL
    port map (CLKI=>__, CLKOP=>__, LOCK=>__);
