-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.11.3.469
-- Module  Version: 2.8
-- Tue Jun 15 14:16:40 2021

-- parameterized module component declaration
component P3038DM_PWMAP
    port (Address: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : P3038DM_PWMAP
    port map (Address(7 downto 0)=>__, Q(7 downto 0)=>__);
