-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.1.454
-- Module  Version: 2.8
-- Mon Apr 14 11:32:25 2025

-- parameterized module component declaration
component PWMAP
    port (Address: in  std_logic_vector(7 downto 0); 
        Q: out  std_logic_vector(7 downto 0));
end component;

-- parameterized module component instance
__ : PWMAP
    port map (Address(7 downto 0)=>__, Q(7 downto 0)=>__);
